server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-MS
          uri: lb://USER-MS
          predicates:
            - Path=/users/**

        - id: HOTEL-MS
          uri: lb://HOTEL-MS
          predicates:
            - Path=/hotels/**

        - id: RATING-MS
          uri: lb://RATING-MS
          predicates:
            - Path=/ratings/**

